### ISSUE TITLE
 x509: certificate has expired or is not yet valid: current time 2021-05-14T00:00:21+08:00 is before 2021-05-14T05:45:12Z

### ISSUE THREAD

**Issue by nicolasni1977** [IronicBadger/ocp4#23]
I am able to stand up lb, bootstrap, master VMs and worker VMs, however I couldn't get api to response check using:

      make wait-for-bootstrap

I gave error message related to certificate shown in the title, sorry I know this might not relate the terraform code, but I would like to know have you encountered the same problem before, how did you fix it?

**Comment by ironicbadger** [comment]
Most likely down to DNS and using a domain other than `openshift.lab.int`

**Comment by cptmorgan-rh** [comment]
@nicolasni1977 - The problem is in the error:

"x509: certificate has expired or is not yet valid: current time 2021-05-14T00:00:21+08:00 is before 2021-05-14T05:45:12Z "

The certificate is valid from a date/time that is after the current date and time. This means you have NTP issues with your bastion or your OCP nodes.

**Comment by nicolasni1977** [comment]
Thank you for the clarification!

**Comment by ironicbadger** [comment]
Let us know if there's an issue here, reopen if needed.
